import { Component, inject, OnInit } from "@angular/core";
import { MapinfoComponent } from "../../z_components/mapinfo/mapinfo.component";
import { TimerRounderComponent } from "../../z_components/timer-rounder/timer-rounder.component";
import { TopscoreComponent } from "../../z_components/topscore/topscore.component";
import { RoundNumberComponent } from "../../z_components/round-number/round-number.component";
import { MapwinsComponent } from "../../z_components/mapwins/mapwins.component";
import { WatermarkComponent } from "../../z_components/watermark/watermark.component";
import { SponsorBoxComponent } from "../../z_components/sponsor-box/sponsor-box.component";
import { RoundreasonsComponent } from "../../z_components/roundreasons/roundreasons.component";
import { ScoreboardComponent } from "../../z_components/scoreboard/scoreboard.component";
import { DataModelService } from "../../services/dataModel.service";
import { CombatTrackerComponent } from "../../z_components/combat-tracker/combat-tracker.component";

@Component({
  selector: "app-match-overlay",
  imports: [
    MapinfoComponent,
    TimerRounderComponent,
    TopscoreComponent,
    RoundNumberComponent,
    MapwinsComponent,
    WatermarkComponent,
    SponsorBoxComponent,
    RoundreasonsComponent,
    ScoreboardComponent,
    CombatTrackerComponent,
  ],
  templateUrl: "./match-overlay.component.html",
  styleUrl: "./match-overlay.component.css",
})
export class MatchOverlayComponent implements OnInit {
  match: any;
  dataModel = inject(DataModelService);

  async ngOnInit(): Promise<void> {
    //setting up with empty match state so certain ui parts dont complain
    this.match = {
      groupCode: "A",
      isRanked: false,
      isRunning: true,
      roundNumber: 10,
      roundPhase: "combat",
      spikeState: { planted: false },
      map: "Ascent",
      switchRound: 12,
      firstOtRound: 25,
      tools: {
        seriesInfo: {
          needed: 3,
          wonLeft: 2,
          wonRight: 2,
          mapInfo: [
            {
              type: "past",
              map: "Fracture",
              left: {
                score: 13,
                logo: "assets/misc/icon.webp",
              },
              right: {
                score: 9,
                logo: "assets/misc/icon.webp",
              },
            },
            {
              type: "present",
              logo: "assets/misc/icon.webp",
            },
            {
              type: "future",
              map: "Haven",
              logo: "assets/misc/icon.webp",
            },
          ],
        },
        seedingInfo: {
          left: "Group A",
          right: "Group B",
        },
        tournamentInfo: {
          name: "",
          logoUrl: "",
          backdropUrl: "",
        },
        timeoutDuration: 60,
        sponsorInfo: {
          enabled: true,
          duration: 5000,
          sponsors: ["assets/misc/logo.webp", "assets/misc/icon.webp"],
        },
        watermarkInfo: {
          customText: "",
          customTextEnabled: false,
          spectraWatermark: true,
        },
      },
      timeoutState: {
        techPause: false,
        leftTeam: false,
        leftTeamStartTime: 0,
        rightTeam: false,
        rightTeamStartTime: 0,
      },
      teams: [
        {
          players: [
            {
              name: "Testg",
              playerId: 0,
              isAlive: true,
              agentInternal: "Vampire",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Operator",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Smonk",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
          ],
          teamName: "The Naturals",
          teamUrl: "assets/misc/icon.webp",
          teamTricode: "INT",
          spentThisRound: 1000,
          isAttacking: false,
          roundsWon: 5,
          roundRecord: [
            { type: "detonated", wasAttack: true, round: 1 },
            { type: "lost", wasAttack: true, round: 2 },
            { type: "kills", wasAttack: true, round: 3 },
            { type: "timeout", wasAttack: true, round: 4 },
            { type: "lost", wasAttack: true, round: 5 },
            { type: "kills", wasAttack: true, round: 6 },
            { type: "lost", wasAttack: true, round: 7 },
            { type: "defused", wasAttack: true, round: 8 },
            { type: "lost", wasAttack: true, round: 9 },
            { type: "lost", wasAttack: true, round: 10 },
            { type: "detonated", wasAttack: true, round: 11 },
            { type: "lost", wasAttack: true, round: 12 },
            { type: "kills", wasAttack: false, round: 13 },
            { type: "timeout", wasAttack: false, round: 14 },
            { type: "lost", wasAttack: false, round: 15 },
            { type: "kills", wasAttack: false, round: 16 },
            { type: "lost", wasAttack: false, round: 17 },
            { type: "defused", wasAttack: false, round: 18 },
            { type: "lost", wasAttack: false, round: 19 },
            { type: "lost", wasAttack: false, round: 20 },
            { type: "lost", wasAttack: true, round: 21 },
            { type: "lost", wasAttack: false, round: 22 },
            { type: "lost", wasAttack: false, round: 23 },
            { type: "defused", wasAttack: false, round: 24 },
            { type: "lost", wasAttack: true, round: 25 },
            { type: "lost", wasAttack: false, round: 26 },
          ],
        },
        {
          players: [
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
          ],
          teamName: "The Zoologists",
          teamUrl: "assets/misc/icon.webp",
          teamTricode: "ZOO",
          spentThisRound: 1000,
          isAttacking: true,
          roundsWon: 5,
          roundRecord: [
            { type: "lost", wasAttack: false, round: 1 },
            { type: "defused", wasAttack: false, round: 2 },
            { type: "lost", wasAttack: false, round: 3 },
            { type: "lost", wasAttack: false, round: 4 },
            { type: "kills", wasAttack: false, round: 5 },
            { type: "lost", wasAttack: false, round: 6 },
            { type: "detonated", wasAttack: false, round: 7 },
            { type: "lost", wasAttack: false, round: 8 },
            { type: "kills", wasAttack: false, round: 9 },
            { type: "timeout", wasAttack: false, round: 10 },
            { type: "lost", wasAttack: false, round: 11 },
            { type: "defused", wasAttack: false, round: 12 },
            { type: "lost", wasAttack: true, round: 13 },
            { type: "lost", wasAttack: true, round: 14 },
            { type: "kills", wasAttack: true, round: 15 },
            { type: "lost", wasAttack: true, round: 16 },
            { type: "detonated", wasAttack: true, round: 17 },
            { type: "lost", wasAttack: true, round: 18 },
            { type: "kills", wasAttack: true, round: 19 },
            { type: "timeout", wasAttack: true, round: 20 },
            { type: "lost", wasAttack: true, round: 21 },
            { type: "kills", wasAttack: true, round: 22 },
            { type: "lost", wasAttack: true, round: 23 },
            { type: "lost", wasAttack: true, round: 24 },
            { type: "kills", wasAttack: false, round: 25 },
            { type: "kills", wasAttack: true, round: 26 },
          ],
        },
      ],
    };
    this.dataModel.match.set(this.match);
  }
}
