import { Component, inject, OnInit } from "@angular/core";
import { MapinfoComponent } from "../../z_components/mapinfo/mapinfo.component";
import { TimerRounderComponent } from "../../z_components/timer-rounder/timer-rounder.component";
import { TopscoreComponent } from "../../z_components/topscore/topscore.component";
import { RoundNumberComponent } from "../../z_components/round-number/round-number.component";
import { MapwinsComponent } from "../../z_components/mapwins/mapwins.component";
import { WatermarkComponent } from "../../z_components/watermark/watermark.component";
import { SponsorBoxComponent } from "../../z_components/sponsor-box/sponsor-box.component";
import { RoundreasonsComponent } from "../../z_components/roundreasons/roundreasons.component";
import { ScoreboardComponent } from "../../z_components/scoreboard/scoreboard.component";
import { DataModelService } from "../../services/dataModel.service";

@Component({
  selector: "app-match-overlay",
  imports: [
    MapinfoComponent,
    TimerRounderComponent,
    TopscoreComponent,
    RoundNumberComponent,
    MapwinsComponent,
    WatermarkComponent,
    SponsorBoxComponent,
    RoundreasonsComponent,
    ScoreboardComponent,
  ],
  templateUrl: "./match-overlay.component.html",
  styleUrl: "./match-overlay.component.css",
})
export class MatchOverlayComponent implements OnInit {
  match: any;
  dataModel = inject(DataModelService);

  async ngOnInit(): Promise<void> {
    //setting up with empty match state so certain ui parts dont complain
    this.match = {
      groupCode: "A",
      isRanked: false,
      isRunning: true,
      roundNumber: 0,
      roundPhase: "LOBBY",
      spikeState: { planted: false },
      map: "Ascent",
      tools: {
        seriesInfo: {
          needed: 1,
          wonLeft: 0,
          wonRight: 0,
          mapInfo: [
            {
              type: "past",
              map: "Fracture",
              left: {
                score: 13,
                logo: "assets/misc/icon.webp",
              },
              right: {
                score: 9,
                logo: "assets/misc/icon.webp",
              },
            },
            {
              type: "present",
              logo: "assets/misc/icon.webp",
            },
            {
              type: "future",
              map: "Haven",
              logo: "assets/misc/icon.webp",
            },
          ],
        },
        seedingInfo: {
          left: "Group A",
          right: "Group B",
        },
        tournamentInfo: {
          name: "",
          logoUrl: "",
          backdropUrl: "",
        },
        timeoutDuration: 60,
        sponsorInfo: {
          enabled: false,
          duration: 5000,
          sponsors: [],
        },
      },
      timeoutState: {
        techPause: false,
        leftTeam: false,
        leftTeamStartTime: 0,
        rightTeam: false,
        rightTeamStartTime: 0,
      },
      teams: [
        {
          players: [
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Vampire",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
          ],
          teamName: "The Naturals",
          teamUrl: "assets/misc/icon.webp",
          teamTricode: "INT",
          spentThisRound: 1000,
          isAttacking: false,
          roundRecord: [
            { type: "detonated", wasAttack: true, round: 1 },
            { type: "lost", wasAttack: true, round: 2 },
            { type: "kills", wasAttack: true, round: 3 },
            { type: "timeout", wasAttack: true, round: 4 },
            { type: "lost", wasAttack: true, round: 5 },
            { type: "kills", wasAttack: false, round: 6 },
            { type: "lost", wasAttack: false, round: 7 },
            { type: "defused", wasAttack: false, round: 8 },
            { type: "lost", wasAttack: false, round: 9 },
            { type: "lost", wasAttack: false, round: 10 },
          ],
        },
        {
          players: [
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
            {
              name: "Test",
              playerId: 0,
              isAlive: true,
              agentInternal: "Wushu",
              isObserved: false,
              armorName: "Heavy",
              money: 2100,
              moneySpent: 2900,
              highestWeapon: "Vandal",
              isCaptain: false,
              currUltPoints: 2,
              maxUltPoints: 7,
              ultReady: false,
              hasSpike: false,
              scoreboardAvailable: true,
              auxiliaryAvailable: {
                health: true,
                abilities: true,
                scoreboard: true,
              },
              kills: 0,
              deaths: 0,
              assists: 0,
              health: 100,
              abilities: {
                grenade: 1,
                ability1: 1,
                ability2: 0,
              },
              iconNameSuffix: "",
            },
          ],
          teamName: "The Zoologists",
          teamUrl: "assets/misc/icon.webp",
          teamTricode: "ZOO",
          spentThisRound: 1000,
          isAttacking: true,
          roundRecord: [
            { type: "lost", wasAttack: false, round: 1 },
            { type: "defused", wasAttack: false, round: 2 },
            { type: "lost", wasAttack: false, round: 3 },
            { type: "lost", wasAttack: false, round: 4 },
            { type: "kills", wasAttack: false, round: 5 },
            { type: "lost", wasAttack: true, round: 6 },
            { type: "detonated", wasAttack: true, round: 7 },
            { type: "lost", wasAttack: true, round: 8 },
            { type: "kills", wasAttack: true, round: 9 },
            { type: "timeout", wasAttack: true, round: 10 },
          ],
        },
      ],
    };
    this.dataModel.match.set(this.match);
  }
}
