name: Lint, Format and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint-format-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run eslint
        run: yarn run lint

      - name: Run prettier
        run: yarn run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Lint and Format

      - name: Run build
        run: yarn build
